prd:
  catalog_name: mlops_prd
  schema_name: moazenim
acc:
  catalog_name: mlops_acc
  schema_name: moazenim
dev:
  catalog_name: mlops_dev
  schema_name: moazenim

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

experiment_name_basic: /Shared/game-sales-prices-basic
experiment_name_custom: /Shared/game-sales-prices-custom

num_features:
  - Rank
  - Year
  - NA_Sales
  - EU_Sales
  - JP_Sales
  - Other_Sales

cat_features:
  - Name
  - Platform
  - Genre
  - Publisher

target: Global_Sales
